package ordertracker

class BrandLoader {
    def load() {
        new Brand(name: 'Velasco', image:'not').save()
        new Brand(name: 'HQ', image:'not').save()
        new Brand(name: 'Coca-Cola', image:'not').save()
        new Brand(name: 'Exotic Liquids', image:'not').save()
        new Brand(name: 'New Orleans Cajun Delights', image:'not').save()
        new Brand(name: 'Grandma Kellys Homestead', image:'not').save()
        new Brand(name: 'Tokyo Traders', image:'not').save()
        new Brand(name: 'Cooperativa de Quesos Las Cabras', image:'not').save()
        new Brand(name: 'Mayumis', image:'not').save()
        new Brand(name: 'Pavlova, Ltd.', image:'not').save()
        new Brand(name: 'Specialty Biscuits, Ltd.', image:'not').save()
        new Brand(name: 'PB Knackebrod AB', image:'not').save()
        new Brand(name: 'Refrescos Americanas LTDA', image:'not').save()
        new Brand(name: 'Heli Subwaren GmbH and Co. KG', image:'not').save()
        new Brand(name: 'Plutzer Lebensmittelgrobmarkte AG', image:'not').save()
        new Brand(name: 'Nord-Ost-Fisch Handelsgesellschaft mbH', image:'not').save()
        new Brand(name: 'Formaggi Fortini s.r.l.', image:'not').save()
        new Brand(name: 'Norske Meierier', image:'not').save()
        new Brand(name: 'Bigfoot Breweries', image:'not').save()
        new Brand(name: 'Svensk Sjofoda AB', image:'not').save()
        new Brand(name: 'Aux joyeux ecclesiastiques', image:'not').save()
        new Brand(name: 'New England Seafood Cannery', image:'not').save()
        new Brand(name: 'Leka Trading', image:'not').save()
        new Brand(name: 'Lyngbysild', image:'not').save()
        new Brand(name: 'Zaanse Snoepfabriek', image:'not').save()
        new Brand(name: 'Karkki Oy', image:'not').save()
        new Brand(name: 'Gday, Mate', image:'not').save()
        new Brand(name: 'Ma Maison', image:'not').save()
        new Brand(name: 'Pasta Buttini s.r.l.', image:'not').save()
        new Brand(name: 'Escargots Nouveaux', image:'not').save()
        new Brand(name: 'Gai paturage', image:'not').save()
        new Brand(name: 'Forets derables', image:'not').save()
    }
}
