package ordertracker

import ordertracker.constants.OrderStates
import ordertracker.util.CalendarDate

class ClientOrderLoader {
    def load() {
        new ClientOrder(seller_id:1, client_id:1, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(0), total_price:252.25).save()
        new ClientOrder(seller_id:1, client_id:2, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(1), total_price:465.00).save()
        new ClientOrder(seller_id:1, client_id:3, state:OrderStates.DESPACHADO.toString(), date:CalendarDate.fromCurrentDate(2),total_price:45.70).save()
        new ClientOrder(seller_id:1, client_id:3, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(3), total_price:64.12).save()
        new ClientOrder(seller_id:1, client_id:4, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(4), total_price:72.13).save()
        new ClientOrder(seller_id:1, client_id:5, state:OrderStates.DESPACHADO.toString(),  date: CalendarDate.fromCurrentDate(5),total_price:80.14).save()
        new ClientOrder(seller_id:1, client_id:6, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(6), total_price:88.15).save()
        new ClientOrder(seller_id:1, client_id:7, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(7), total_price:96.16).save()
        new ClientOrder(seller_id:1, client_id:8, state:OrderStates.DESPACHADO.toString(),  date: CalendarDate.fromCurrentDate(-1),total_price:104.17).save()
        new ClientOrder(seller_id:1, client_id:9, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(-2), total_price:112.18).save()
        new ClientOrder(seller_id:1, client_id:10, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(-3), total_price:120.19).save()
        new ClientOrder(seller_id:1, client_id:11, state:OrderStates.DESPACHADO.toString(), date: CalendarDate.fromCurrentDate(-6), total_price:128.20).save()
        new ClientOrder(seller_id:1, client_id:12, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(-7), total_price:136.21).save()
        new ClientOrder(seller_id:1, client_id:13, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(-8), total_price:144.22).save()
        new ClientOrder(seller_id:1, client_id:14, state:OrderStates.DESPACHADO.toString(), date: CalendarDate.fromCurrentDate(8),  total_price:152.23).save()

        new ClientOrder(seller_id:4, client_id:15, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(0), total_price:252.25).save()
        new ClientOrder(seller_id:4, client_id:16, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(1), total_price:465.00).save()
        new ClientOrder(seller_id:4, client_id:17, state:OrderStates.DESPACHADO.toString(), date:CalendarDate.fromCurrentDate(2),total_price:45.70).save()
        new ClientOrder(seller_id:4, client_id:18, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(3), total_price:64.12).save()
        new ClientOrder(seller_id:4, client_id:19, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(4), total_price:72.13).save()
        new ClientOrder(seller_id:4, client_id:20, state:OrderStates.DESPACHADO.toString(),  date: CalendarDate.fromCurrentDate(5),total_price:80.14).save()
        new ClientOrder(seller_id:4, client_id:21, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(6), total_price:88.15).save()
        new ClientOrder(seller_id:4, client_id:22, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(7), total_price:96.16).save()
        new ClientOrder(seller_id:4, client_id:23, state:OrderStates.DESPACHADO.toString(),  date: CalendarDate.fromCurrentDate(-1),total_price:104.17).save()
        new ClientOrder(seller_id:4, client_id:24, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(-2), total_price:112.18).save()
        new ClientOrder(seller_id:4, client_id:25, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(-3), total_price:120.19).save()
        new ClientOrder(seller_id:4, client_id:26, state:OrderStates.DESPACHADO.toString(), date: CalendarDate.fromCurrentDate(-6), total_price:128.20).save()
        new ClientOrder(seller_id:4, client_id:27, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(-7), total_price:136.21).save()
        new ClientOrder(seller_id:4, client_id:28, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(-8), total_price:144.22).save()
        new ClientOrder(seller_id:4, client_id:29, state:OrderStates.DESPACHADO.toString(), date: CalendarDate.fromCurrentDate(8),  total_price:152.23).save()

        new ClientOrder(seller_id:3, client_id:30, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(0), total_price:252.25).save()
        new ClientOrder(seller_id:3, client_id:31, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(1), total_price:465.00).save()
        new ClientOrder(seller_id:3, client_id:32, state:OrderStates.DESPACHADO.toString(), date:CalendarDate.fromCurrentDate(2),total_price:45.70).save()
        new ClientOrder(seller_id:3, client_id:33, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(3), total_price:64.12).save()
        new ClientOrder(seller_id:3, client_id:34, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(4), total_price:72.13).save()
        new ClientOrder(seller_id:3, client_id:35, state:OrderStates.DESPACHADO.toString(),  date: CalendarDate.fromCurrentDate(5),total_price:80.14).save()
        new ClientOrder(seller_id:3, client_id:36, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(6), total_price:88.15).save()
        new ClientOrder(seller_id:3, client_id:37, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(7), total_price:96.16).save()
        new ClientOrder(seller_id:3, client_id:38, state:OrderStates.DESPACHADO.toString(),  date: CalendarDate.fromCurrentDate(-1),total_price:104.17).save()
        new ClientOrder(seller_id:3, client_id:39, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(-2), total_price:112.18).save()
        new ClientOrder(seller_id:3, client_id:40, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(-3), total_price:120.19).save()
        new ClientOrder(seller_id:3, client_id:41, state:OrderStates.DESPACHADO.toString(), date: CalendarDate.fromCurrentDate(-6), total_price:128.20).save()
        new ClientOrder(seller_id:3, client_id:42, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(-7), total_price:136.21).save()
        new ClientOrder(seller_id:3, client_id:40, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(-8), total_price:144.22).save()
        new ClientOrder(seller_id:3, client_id:44, state:OrderStates.DESPACHADO.toString(), date: CalendarDate.fromCurrentDate(8),  total_price:152.23).save()

        new ClientOrder(seller_id:2, client_id:45, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(0), total_price:252.25).save()
        new ClientOrder(seller_id:2, client_id:46, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(1), total_price:465.00).save()
        new ClientOrder(seller_id:2, client_id:47, state:OrderStates.DESPACHADO.toString(), date:CalendarDate.fromCurrentDate(2),total_price:45.70).save()
        new ClientOrder(seller_id:2, client_id:48, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(3), total_price:64.12).save()
        new ClientOrder(seller_id:2, client_id:49, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(4), total_price:72.13).save()
        new ClientOrder(seller_id:2, client_id:50, state:OrderStates.DESPACHADO.toString(),  date: CalendarDate.fromCurrentDate(5),total_price:80.14).save()
        new ClientOrder(seller_id:2, client_id:51, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(6), total_price:88.15).save()
        new ClientOrder(seller_id:2, client_id:52, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(7), total_price:96.16).save()
        new ClientOrder(seller_id:2, client_id:53, state:OrderStates.DESPACHADO.toString(),  date: CalendarDate.fromCurrentDate(-1),total_price:104.17).save()
        new ClientOrder(seller_id:2, client_id:54, state:OrderStates.SOLICITADO.toString(), date: CalendarDate.fromCurrentDate(-2), total_price:112.18).save()
        new ClientOrder(seller_id:2, client_id:55, state:OrderStates.CANCELADO.toString(), date: CalendarDate.fromCurrentDate(-3), total_price:120.19).save()
        new ClientOrder(seller_id:2, client_id:56, state:OrderStates.DESPACHADO.toString(), date: CalendarDate.fromCurrentDate(-6), total_price:128.20).save()
    }
}
