package ordertracker

class ClientOrderLoader {
    def load() {
        new ClientOrder(seller_id:1, client_id:1, state:'pendiente', total_price:252.25).save()
        new ClientOrder(seller_id:1, client_id:2, state:'completa', total_price:465.00).save()
        new ClientOrder(seller_id:2, client_id:3, state:'cancelada', total_price:45.70).save()
        new ClientOrder(seller_id:3, client_id:3, state:'cancelada', total_price:64.12).save()
        new ClientOrder(seller_id:4, client_id:4, state:'pendiente', total_price:72.13).save()
        new ClientOrder(seller_id:5, client_id:5, state:'completa', total_price:80.14).save()
        new ClientOrder(seller_id:6, client_id:6, state:'cancelada', total_price:88.15).save()
        new ClientOrder(seller_id:7, client_id:7, state:'pendiente', total_price:96.16).save()
        new ClientOrder(seller_id:8, client_id:8, state:'completa', total_price:104.17).save()
        new ClientOrder(seller_id:8, client_id:9, state:'cancelada', total_price:112.18).save()
        new ClientOrder(seller_id:8, client_id:10, state:'pendiente', total_price:120.19).save()
        new ClientOrder(seller_id:8, client_id:11, state:'completa', total_price:128.20).save()
        new ClientOrder(seller_id:8, client_id:12, state:'cancelada', total_price:136.21).save()
        new ClientOrder(seller_id:8, client_id:13, state:'pendiente', total_price:144.22).save()
        new ClientOrder(seller_id:8, client_id:14, state:'completa', total_price:152.23).save()
        new ClientOrder(seller_id:8, client_id:15, state:'cancelada', total_price:160.24).save()
        new ClientOrder(seller_id:8, client_id:16, state:'pendiente', total_price:168.25).save()
        new ClientOrder(seller_id:8, client_id:17, state:'completa', total_price:176.26).save()
        new ClientOrder(seller_id:9, client_id:18, state:'cancelada', total_price:184.27).save()
        new ClientOrder(seller_id:10, client_id:19, state:'pendiente', total_price:192.28).save()
        new ClientOrder(seller_id:11, client_id:20, state:'completa', total_price:200.29).save()
        new ClientOrder(seller_id:12, client_id:21, state:'cancelada', total_price:208.30).save()
        new ClientOrder(seller_id:13, client_id:22, state:'pendiente', total_price:216.31).save()
        new ClientOrder(seller_id:14, client_id:23, state:'completa', total_price:224.32).save()
        new ClientOrder(seller_id:15, client_id:24, state:'cancelada', total_price:232.33).save()
        new ClientOrder(seller_id:16, client_id:25, state:'pendiente', total_price:240.34).save()
        new ClientOrder(seller_id:17, client_id:26, state:'completa', total_price:248.35).save()
        new ClientOrder(seller_id:18, client_id:27, state:'cancelada', total_price:256.36).save()
        new ClientOrder(seller_id:19, client_id:28, state:'pendiente', total_price:264.37).save()
        new ClientOrder(seller_id:20, client_id:29, state:'completa', total_price:272.38).save()
        new ClientOrder(seller_id:21, client_id:30, state:'cancelada', total_price:280.39).save()
        new ClientOrder(seller_id:22, client_id:31, state:'pendiente', total_price:288.40).save()
        new ClientOrder(seller_id:23, client_id:32, state:'completa', total_price:296.41).save()
        new ClientOrder(seller_id:24, client_id:33, state:'cancelada', total_price:304.42).save()
        new ClientOrder(seller_id:25, client_id:34, state:'pendiente', total_price:312.43).save()
        new ClientOrder(seller_id:26, client_id:35, state:'completa', total_price:320.44).save()
        new ClientOrder(seller_id:27, client_id:36, state:'cancelada', total_price:328.45).save()
        new ClientOrder(seller_id:28, client_id:37, state:'pendiente', total_price:336.46).save()
        new ClientOrder(seller_id:29, client_id:38, state:'completa', total_price:344.47).save()
        new ClientOrder(seller_id:30, client_id:39, state:'cancelada', total_price:352.48).save()
        new ClientOrder(seller_id:31, client_id:40, state:'pendiente', total_price:360.49).save()
        new ClientOrder(seller_id:32, client_id:41, state:'completa', total_price:368.50).save()
        new ClientOrder(seller_id:33, client_id:42, state:'cancelada', total_price:376.51).save()
        new ClientOrder(seller_id:34, client_id:43, state:'pendiente', total_price:384.52).save()
        new ClientOrder(seller_id:35, client_id:44, state:'completa', total_price:392.53).save()
        new ClientOrder(seller_id:36, client_id:45, state:'cancelada', total_price:400.54).save()
        new ClientOrder(seller_id:37, client_id:46, state:'pendiente', total_price:408.55).save()
        new ClientOrder(seller_id:38, client_id:47, state:'completa', total_price:416.56).save()
        new ClientOrder(seller_id:39, client_id:48, state:'cancelada', total_price:424.57).save()
        new ClientOrder(seller_id:40, client_id:49, state:'pendiente', total_price:432.58).save()
        new ClientOrder(seller_id:41, client_id:50, state:'completa', total_price:440.59).save()
        new ClientOrder(seller_id:42, client_id:51, state:'cancelada', total_price:448.60).save()
        new ClientOrder(seller_id:43, client_id:52, state:'pendiente', total_price:456.61).save()
        new ClientOrder(seller_id:44, client_id:53, state:'completa', total_price:464.62).save()
        new ClientOrder(seller_id:45, client_id:54, state:'cancelada', total_price:472.63).save()
        new ClientOrder(seller_id:46, client_id:55, state:'pendiente', total_price:480.64).save()
        new ClientOrder(seller_id:47, client_id:56, state:'completa', total_price:488.65).save()
    }
}
