package ordertracker

class ProductLoader {
    def load() {
        new Product(name:'mesa', brand_id:1, image:'images/product/1', category:'muebles', characteristic:'madera aglomerada', stock:20, price:600.00, state:'disponible').save()
        new Product(name:'silla', brand_id:1, image:'images/product/2', category:'muebles', characteristic:'madera aglomerada',stock:500, price:150.00, state:'disponible').save()
        new Product(name:'escritorio', brand_id:1, image:'images/product/3', category:'muebles', characteristic:'madera aglomerada', stock:10, price:1500.00, state:'disponible').save()
        new Product(name:'mesa', brand_id:2, image:'images/product/4', category:'muebles', characteristic:'madera roble', stock:5, price:600.00, state:'disponible').save()
        new Product(name:'Coca-Cola', brand_id:3, image:'images/product/5', category:'bebidas', characteristic:'botella 500ml', stock:500, price:15.50, state:'disponible').save()
        new Product(name:'Coca-Cola', brand_id:3, image:'images/product/6', category:'bebidas', characteristic:'botella 1500ml', stock:700, price:23.65, state:'disponible').save()
        new Product(name:'Fanta', brand_id:3, image:'images/product/7', category:'bebidas', characteristic:'botella 1500ml', stock:800, price:24.43, state:'disponible').save()
        new Product(name:'Sprite', brand_id:3, image:'images/product/8', category:'bebidas', characteristic:'botella 1500ml', stock:800, price:23.85, state:'disponible').save()
        new Product(name:'ALIMENTO P/ FINES MÉDICOS INFANTRINI P/ LACTANTES FCO X 100 ML', brand_id:1, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:2, price:50.00, state:'disponible').save()
        new Product(name:'BENEDICT CUALITATIVO 120 ML', brand_id:2, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:4, price:50.05, state:'disponible').save()
        new Product(name:'BIOMODULINAT (FRACCIÓN TIMICA) 1MG/ML INYECTABLE BULBO X 3 ML ', brand_id:3, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:6, price:50.10, state:'disponible').save()
        new Product(name:'CARBON ACTIVADO BOLSAS 1 KG', brand_id:4, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:8, price:50.15, state:'disponible').save()
        new Product(name:'CITRATO DE POTASIO TAB', brand_id:5, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:10, price:50.20, state:'disponible').save()
        new Product(name:'DIATRIZOATO COMPUESTO X 20 ML X 1 AMP.', brand_id:6, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:12, price:50.25, state:'disponible').save()
        new Product(name:'DIMEGLUMINA (GADOLINE) 469MG SOL INY IV EST X 1 VIAL X 15ML', brand_id:7, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:14, price:50.30, state:'disponible').save()
        new Product(name:'FACTOR DE TRANSFERENCIA 1U BBO LIOFILIZADO (HEBERTRANS)', brand_id:8, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:16, price:50.35, state:'disponible').save()
        new Product(name:'FENTANILO 0,05 MG/ML X 3 ML ', brand_id:9, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:18, price:50.40, state:'disponible').save()
        new Product(name:'FLUORESCEINA 20% X 5 ML AMP.', brand_id:10, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:20, price:50.45, state:'disponible').save()
        new Product(name:'FORFER EST.X  2 BLISTER X 10 TABS. C/U (75MG FUMARATO FERROSOy 0,1MG ACIDO FOLICO) ', brand_id:11, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:22, price:50.50, state:'disponible').save()
        new Product(name:'IOPRAMIDE 370 X 100 ML BBO ', brand_id:12, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:24, price:50.55, state:'disponible').save()
        new Product(name:'IVERMECTINA 6MG TABLETAS', brand_id:13, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:26, price:50.60, state:'disponible').save()
        new Product(name:'LACTOSAN', brand_id:14, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:28, price:50.65, state:'disponible').save()
        new Product(name:'LETROZOLE 2,5 MG  TABLETAS', brand_id:15, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:30, price:50.70, state:'disponible').save()
        new Product(name:'LIKROLOL x 20ML AMPULA', brand_id:16, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:32, price:125.55, state:'disponible').save()
        new Product(name:'MATERLAC (CEREAL LACTEADO ENRIQUECIDO BOLSA X 1000 G)', brand_id:17, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:34, price:125.56, state:'disponible').save()
        new Product(name:'MILUPA PKU-3  LATA X 500 GRAMOS', brand_id:18, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:36, price:125.57, state:'disponible').save()
        new Product(name:'MORFINA 2 MG BBO X 5 ML LIOFILIZADA', brand_id:19, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:38, price:125.58, state:'disponible').save()
        new Product(name:'MUFER X 100 TABLETAS', brand_id:20, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:40, price:125.59, state:'disponible').save()
        new Product(name:'NUTRIFORTE  X 100 TABLETAS', brand_id:21, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:42, price:125.60, state:'disponible').save()
        new Product(name:'NUTRINI ESTÁNDAR BOLSA X 500', brand_id:22, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:44, price:125.61, state:'disponible').save()
        new Product(name:'OXIDO NITROSO  KG', brand_id:23, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:46, price:125.62, state:'disponible').save()
        new Product(name:'PETIDINA 100 MG X 2 ML AMPS.', brand_id:24, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:48, price:125.63, state:'disponible').save()
        new Product(name:'PETIDINA 50 MG X 1 ML AMPS.', brand_id:25, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:50, price:125.64, state:'disponible').save()
        new Product(name:'POLIVIT X 100 TABLETAS (POLIVITAMI NICAS)', brand_id:26, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:52, price:125.65, state:'disponible').save()
        new Product(name:'PRENATAL EST. X 3 BLISTER X 10 TABLETAS C/U', brand_id:27, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:54, price:846.00, state:'disponible').save()
        new Product(name:'SOLUCION RINGER CON LACTATO X 1000 ML', brand_id:28, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:56, price:846.33, state:'disponible').save()
        new Product(name:'SULFATO DE BARIO ENEMA POLVO X 1000 G.', brand_id:6, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:58, price:846.66, state:'disponible').save()
        new Product(name:'TIOMERSAL TINTURA FCO. X 30 ML', brand_id:7, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:60, price:846.99, state:'disponible').save()
        new Product(name:'VACUNA ANTIDIFTÉRICA, ANTITETÁNICA (DT) BBO X 10 DOSIS.(VA-DIFTET)', brand_id:8, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:62, price:846.132, state:'disponible').save()
        new Product(name:'VACUNA ANTIGRIPAL X 250 DOSIS (ADULTO)', brand_id:9, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:64, price:846.165, state:'disponible').save()
        new Product(name:'VACUNA ANTIRRABICA CRL HUMANA LIQ. BULBO', brand_id:10, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:66, price:846.198, state:'disponible').save()
        new Product(name:'VACUNA ANTITETÁNICA,ANTIDIFTERICA Y ANTIPERTUSSIS (DPT) BBO X10 DOSIS.', brand_id:11, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:68, price:846.231, state:'disponible').save()
        new Product(name:'VACUNA ANTITIFOÍDICA DE POLISACÁRIDO Vi BBO X 10 DOSIS (VAX-TyVi).', brand_id:12, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:70, price:846.264, state:'disponible').save()
        new Product(name:'VACUNA C/ FIEBRE AMARILLA 5 DOSIS/AMP CAJA', brand_id:13, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:72, price:846.297, state:'disponible').save()
        new Product(name:'VACUNA PENTAVALENTE DPT+HB+Hib BBO X 7 DOSIS (HEBERPENTA)', brand_id:14, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:74, price:846.330, state:'disponible').save()
        new Product(name:'VACUNA TOXOIDE TETANICO BBOX 10 DOSIS.', brand_id:15, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:76, price:846.363, state:'disponible').save()
        new Product(name:'VACUNA TRIPLE VIRAL BBO. X 10 DOSIS (PRS)', brand_id:16, image:'images/product/1', category:'medicamentos', characteristic:'farmacéuticos',stock:78, price:846.396, state:'disponible').save()
    }
}



