package ordertracker

class SellerLoader {
    def load() {
        new Seller(document_number:33457893, name:'Martin Horacio Gainsborough', zone:'buenos aires').save()
        new Seller(document_number:31546458, name:'Martin Edgardo Quesnel', zone:'zona oeste').save()
        new Seller(document_number:37876012, name:'Barbara Armantrout', zone:'zona sur').save()
        new Seller(document_number:39856134, name:'Uriel Kahn', zone:'zona norte').save()
        new Seller(document_number:30123456, name:'Jose Vasconcelos', zone:'zona oeste').save()
        new Seller(document_number:29876012, name:'Gabriele Picco', zone:'zona sur').save()
        new Seller(document_number:27856134, name:'Mark Haddon', zone:'zona norte').save()
        new Seller(document_number:29846527, name:'Adolfo Perez Esquivel', zone:'zona oeste').save()
        new Seller(document_number:28456791, name:'Al Gore', zone:'zona norte').save()
        new Seller(document_number:28456862, name:'Albert Lutuli', zone:'zona norte').save()
        new Seller(document_number:28456933, name:'Albert Schweitzer', zone:'zona norte').save()
        new Seller(document_number:28457004, name:'Alfonso Garcia Robles', zone:'zona norte').save()
        new Seller(document_number:28457075, name:'Alto Comisionado de las Naciones Unidas para los Refugiados', zone:'zona norte').save()
        new Seller(document_number:28457146, name:'Alva Myrdal', zone:'zona norte').save()
        new Seller(document_number:28457217, name:'American Friends Service Committee', zone:'zona norte').save()
        new Seller(document_number:28457288, name:'Amnistia Internacional', zone:'zona norte').save()
        new Seller(document_number:28457359, name:'Andrei Sakharov', zone:'zona norte').save()
        new Seller(document_number:28457430, name:'Anwar El Sadat', zone:'zona norte').save()
        new Seller(document_number:28457501, name:'Asociacion Internacional de Medicos para la Prevencion de la Guerra Nuclear', zone:'zona oeste').save()
        new Seller(document_number:28457572, name:'Aung San Suu Kyi', zone:'zona oeste').save()
        new Seller(document_number:28457643, name:'Barack Obama', zone:'zona oeste').save()
        new Seller(document_number:28457714, name:'Betty Williams', zone:'zona oeste').save()
        new Seller(document_number:28457785, name:'Campaña Internacional para la Prohibicion de las Minas Antipersona', zone:'zona oeste').save()
        new Seller(document_number:28457856, name:'Carlos Filipe Ximenes Belo', zone:'zona oeste').save()
        new Seller(document_number:28457927, name:'Comite Internacional de la Cruz Roja', zone:'zona oeste').save()
        new Seller(document_number:28457998, name:'Conferencia Pugwash', zone:'zona oeste').save()
        new Seller(document_number:28458069, name:'Cordell Hull', zone:'zona oeste').save()
        new Seller(document_number:28458140, name:'Dag Hammarskjold', zone:'zona oeste').save()
        new Seller(document_number:28458211, name:'David Trimble', zone:'zona oeste').save()
        new Seller(document_number:28458282, name:'Desmond Tutu', zone:'zona oeste').save()
        new Seller(document_number:28458353, name:'Eisaku Sato', zone:'zona oeste').save()
        new Seller(document_number:28458424, name:'Elie Wiesel', zone:'zona oeste').save()
        new Seller(document_number:28458495, name:'Emily Greene Balch', zone:'zona oeste').save()
        new Seller(document_number:28458566, name:'Federacion Internacional de Sociedades de la Cruz Roja y de la Media Luna Roja', zone:'zona oeste').save()
        new Seller(document_number:28458637, name:'Fondo de Naciones Unidas para la Infancia (Unicef)', zone:'zona oeste').save()
        new Seller(document_number:28458708, name:'Frederik Willem de Klerk', zone:'zona oeste').save()
        new Seller(document_number:28458779, name:'Friends Service Council', zone:'zona oeste').save()
        new Seller(document_number:28458850, name:'Fuerzas de paz de las Naciones Unidas', zone:'zona oeste').save()
        new Seller(document_number:28458921, name:'George Marshall', zone:'zona oeste').save()
        new Seller(document_number:28458992, name:'Georges Pire', zone:'zona oeste').save()
        new Seller(document_number:28459063, name:'Grameen Bank', zone:'zona oeste').save()
        new Seller(document_number:28459134, name:'Henry Kissinger', zone:'zona oeste').save()
        new Seller(document_number:28459205, name:'Intergovernmental Panel on Climate Change', zone:'zona oeste').save()
        new Seller(document_number:28459276, name:'Jimmy Carter', zone:'zona norte').save()
        new Seller(document_number:28459347, name:'Jody Williams', zone:'zona norte').save()
        new Seller(document_number:28459418, name:'John Boyd Orr', zone:'zona norte').save()
        new Seller(document_number:28459489, name:'John Hume', zone:'zona norte').save()
        new Seller(document_number:28459560, name:'John Mott', zone:'zona norte').save()
        new Seller(document_number:28459631, name:'Jose Ramos-Horta', zone:'zona norte').save()
        new Seller(document_number:28459702, name:'Joseph Rotblat', zone:'zona norte').save()
        new Seller(document_number:28459773, name:'Kim Dae Jung', zone:'zona norte').save()
        new Seller(document_number:28459844, name:'Kofi Annan', zone:'zona norte').save()
        new Seller(document_number:28459915, name:'Le Duc Tho', zone:'zona norte').save()
        new Seller(document_number:28459986, name:'Lech Walesa', zone:'zona sur').save()
        new Seller(document_number:28460057, name:'Leon Jouhaux', zone:'zona sur').save()
        new Seller(document_number:28460128, name:'Lester B. Pearson', zone:'zona sur').save()
        new Seller(document_number:28460199, name:'Linus Pauling', zone:'zona sur').save()
        new Seller(document_number:28460270, name:'Liu Xiaobo', zone:'zona sur').save()
        new Seller(document_number:28460341, name:'Mairead Corrigan', zone:'zona sur').save()
        new Seller(document_number:28460412, name:'Martin Luther King, Jr.', zone:'zona sur').save()
        new Seller(document_number:28460483, name:'Martti Ahtisaari', zone:'zona sur').save()
        new Seller(document_number:28460554, name:'Medicos Sin Fronteras', zone:'zona sur').save()
        new Seller(document_number:28460625, name:'Menachem Begin', zone:'zona sur').save()
        new Seller(document_number:28460696, name:'Mikhail Gorbachev', zone:'zona sur').save()
        new Seller(document_number:28460767, name:'Mohamed ElBaradei', zone:'zona sur').save()
        new Seller(document_number:28460838, name:'Muhammad Yunus', zone:'zona sur').save()
        new Seller(document_number:28460909, name:'Nelson Mandela', zone:'zona sur').save()
        new Seller(document_number:28461051, name:'Norman Borlaug', zone:'zona sur').save()
        new Seller(document_number:28461122, name:'Organismo Internacional de Energia Atomica', zone:'zona sur').save()
        new Seller(document_number:28461193, name:'Organizacion de las Naciones Unidas', zone:'zona sur').save()
        new Seller(document_number:28461264, name:'Organizacion Internacional del Trabajo', zone:'zona sur').save()
        new Seller(document_number:28461335, name:'Óscar Arias', zone:'Zona noroeste').save()
        new Seller(document_number:28461406, name:'Philip J. Noel-Baker', zone:'Zona noroeste').save()
        new Seller(document_number:28461477, name:'Ralph Bunche', zone:'Zona noroeste').save()
        new Seller(document_number:28461548, name:'Rene Cassin', zone:'Zona noroeste').save()
        new Seller(document_number:28461619, name:'Rigoberta Menchu', zone:'Zona noroeste').save()
        new Seller(document_number:28461690, name:'Sean MacBride', zone:'Zona noroeste').save()
        new Seller(document_number:28461761, name:'Shimon Peres', zone:'Zona noroeste').save()
        new Seller(document_number:28461832, name:'Shirin Ebadi', zone:'Zona noroeste').save()
        new Seller(document_number:28461903, name:'Tenzin Gyatso, el XIV Dalai Lama', zone:'Zona noroeste').save()
        new Seller(document_number:28461974, name:'Teresa de Calcuta', zone:'Zona noroeste').save()
        new Seller(document_number:28462045, name:'Wangari Maathai', zone:'Zona noroeste').save()
        new Seller(document_number:28462116, name:'Willy Brandt', zone:'Zona noroeste').save()
        new Seller(document_number:28462187, name:'Yasser Arafat', zone:'Zona noroeste').save()
        new Seller(document_number:28462258, name:'Yitzhak Rabin', zone:'Zona noroeste').save()
    }
}
